meta_title: "Jouw Stek"
meta_description: "Een kwart van de Nederlanders kent z'n buren nauwelijks. Hoe zit dat bij jou? Jouw Stek zorgt voor onverwachte ontmoetingen in buurten. En wat is nou een betere ontmoetingsplek dan in de tuin?"
meta_image: "banner.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@DeGezondeStad" # indispensable pour les Twitter Cards

